# Generated by Django 5.2.1 on 2025-06-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrecipitationInterpolated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('short_name', models.CharField(default=None, max_length=50)),
                ('level', models.CharField(default=None, max_length=20)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RadiationInterpolated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('short_name', models.CharField(default=None, max_length=50)),
                ('level', models.CharField(default=None, max_length=20)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Albedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('valid_time', 'latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='CAPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('valid_time', 'latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='CloudCoverInterpolated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('short_name', models.CharField(default=None, max_length=50)),
                ('level', models.CharField(default=None, max_length=20)),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('valid_time', 'latitude', 'longitude', 'level')},
            },
        ),
        migrations.CreateModel(
            name='GRIBCycleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cycle_00', models.CharField(default='pending', max_length=20)),
                ('cycle_06', models.CharField(default='pending', max_length=20)),
                ('cycle_12', models.CharField(default='pending', max_length=20)),
                ('cycle_18', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('short_name', models.CharField(default=None, max_length=50)),
                ('level', models.CharField(max_length=10)),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('valid_time', 'latitude', 'longitude', 'level', 'short_name')},
            },
        ),
        migrations.CreateModel(
            name='InterpolatedVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('level', models.CharField(default=None, max_length=20)),
                ('variable', models.CharField(default=None, max_length=50)),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('valid_time', 'latitude', 'longitude', 'level', 'variable')},
            },
        ),
        migrations.CreateModel(
            name='Precipitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('short_name', models.CharField(default=None, max_length=50)),
                ('level', models.CharField(max_length=20)),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('valid_time', 'latitude', 'longitude', 'level', 'short_name')},
            },
        ),
        migrations.CreateModel(
            name='Radiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('short_name', models.CharField(default=None, max_length=50)),
                ('level', models.CharField(max_length=10)),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('valid_time', 'latitude', 'longitude', 'level', 'short_name')},
            },
        ),
        migrations.CreateModel(
            name='SunshineDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('valid_time', 'latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('short_name', models.CharField(default=None, max_length=50)),
                ('level', models.CharField(max_length=10)),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('valid_time', 'latitude', 'longitude', 'level', 'short_name')},
            },
        ),
        migrations.CreateModel(
            name='TemperatureInterpolated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('short_name', models.CharField(default=None, max_length=50)),
                ('level', models.CharField(default=None, max_length=20)),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('valid_time', 'latitude', 'longitude', 'level')},
            },
        ),
        migrations.CreateModel(
            name='TotalCloudCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('short_name', models.CharField(default=None, max_length=50)),
                ('level', models.CharField(default=None, max_length=10)),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('valid_time', 'latitude', 'longitude', 'level', 'short_name')},
            },
        ),
        migrations.CreateModel(
            name='WindComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('level', models.CharField(max_length=50)),
                ('u_value', models.FloatField()),
                ('v_value', models.FloatField()),
            ],
            options={
                'unique_together': {('valid_time', 'latitude', 'longitude', 'level')},
            },
        ),
        migrations.CreateModel(
            name='WindGust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('valid_time', 'latitude', 'longitude')},
            },
        ),
    ]
