# Generated by Django 5.2.1 on 2025-06-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wind_data_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='precipitationinterpolated',
            unique_together={('valid_time', 'latitude', 'longitude', 'level', 'short_name')},
        ),
        migrations.AlterUniqueTogether(
            name='radiationinterpolated',
            unique_together={('valid_time', 'latitude', 'longitude', 'level', 'short_name')},
        ),
    ]
