# Generated by Django 5.2.1 on 2025-05-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_data_processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winddata10m',
            name='u_value',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='winddata10m',
            name='v_value',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='winddata10m',
            unique_together={('valid_time', 'latitude', 'longitude')},
        ),
        migrations.CreateModel(
            name='GRIBCycleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cycle_00', models.CharField(default='pending', max_length=20)),
                ('cycle_06', models.CharField(default='pending', max_length=20)),
                ('cycle_12', models.CharField(default='pending', max_length=20)),
                ('cycle_18', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='WindDataSpatialInterpolated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('wind_speed', models.FloatField()),
            ],
            options={
                'unique_together': {('valid_time', 'latitude', 'longitude')},
            },
        ),
    ]
