# Generated by Django 5.2.1 on 2025-06-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_data_processing', '0002_alter_precipitationinterpolated_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='albedo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='cape',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sunshineduration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='albedo',
            name='level',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='cape',
            name='level',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='sunshineduration',
            name='level',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='albedo',
            unique_together={('valid_time', 'latitude', 'longitude', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='cape',
            unique_together={('valid_time', 'latitude', 'longitude', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='sunshineduration',
            unique_together={('valid_time', 'latitude', 'longitude', 'level')},
        ),
    ]
