# Generated by Django 5.2.1 on 2025-06-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_data_processing', '0003_alter_albedo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='windgust',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='windgust',
            name='level',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='windgust',
            unique_together={('valid_time', 'latitude', 'longitude', 'level')},
        ),
    ]
